### ISSUE TITLE
Why is term_child behavior different in shutdown_everything_now!() ?

### ISSUE THREAD

**Issue by iceberg901** [mbr84/heroku-resque-pool#1]
1. Is it intentional or an oversight that the choice of which signal to send based on the value of `term_child` works opposite in shutdown_everything_now!() to how it works everywhere else?  In only that one method, the workers are sent `QUIT` if term_child is true, but everywhere else workers are sent `TERM` if term_child is true.  If this is actually intentional, what is the reason?

    https://github.com/mbr84/heroku-resque-pool/blob/master/lib/resque/pool.rb#L307-L311

1. Is it necessary to run with the `--term-graceful-wait` or `--term-graceful` command line options for this to work as expected on Heroku?

1. Finally, is this gem still necessary?  Current `resque-pool` README seems to suggest that they're aware of how to handle Heroku signals properly:

    > If the environment variable TERM_CHILD is set, QUIT and TERM will respond as defined by Resque 1.22 and above. See http://hone.heroku.com/resque/2012/08/21/resque-signals.html for details, overriding any command-line configuration for TERM. Setting TERM_CHILD tells us you know what you're doing.

**Comment by mbr84** [comment]
1. ```shutdown_everything_now!``` is a part of the original resque-pool patch, so I can only speculate that child processes are sent quit rather than term in this method because the method is called when a parent process receives a ```QUIT``` signal from Heroku. You can read about the differences between SIGTERM and SIGQUIT [here](https://unix.stackexchange.com/questions/251195/difference-between-less-violent-kill-signal-hup-1-int-2-and-term-15), but in general QUIT sent when a process is malfunctioning, and not in a case where graceful shutdown would be appropriate. 
2. I haven't found those options to be necessary
3. There is discussion of Heroku signals in the resque-pool readme, and there's some signal-handling logic in the resque-pool patch; but none of it occurs on the ```Worker``` class. So for example, when, in resque-pool, the parent process receives a SIGTERM, it sends "signals" to its children instructing them how to shut down. But since Heroku sends SIGTERMs to parent and child processes alike, and nothing is being done by Resque in the ```Worker``` to trap ```trap``` those incoming signals, the parent's shutdown instructions are just being overridden. 
That being said, it looks like there have been some updates to resque-pool in the last few months. I can't speak to those. What I can tell you for certain, is that I removed resque-pool from a project at work and made this gem to replace it, because child processes in resque-pool were being killed before they could complete by Heroku dyno restarts and worker rescales

**Comment by iceberg901** [comment]
@mbr84 thanks for the quick feedback!

A few follow ups:

1. What, then, does your gem do that I wouldn’t get by including `resque-heroku-signals` directly?
2. If I run a separate process where I start a resque worker outside of a pool, will your gem also correctly patch that case, or do I need to also include `resque-heroku-signals` for that to work correctly?
3. What were the symptoms of the problem you had before using this gem? We’re seeing a lot of Resque::PruneDeadWorkerDirtyExit errors when scaling worker dyno counts up and down - is that consistent with the problem you encountered?

Thanks for your assistance!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mbr84** [comment]
1. I forget.
2. That should be fine but I haven’t tried it. Since you can have separate
worker pools, I’ve tended to use pool for everything or not at all.
3. That’s the exact use case that prompted me to bundle this up.

**Comment by iceberg901** [comment]
Thanks! Really appreciate the details.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
